"""Phase 0 baseline inventory generator.

Walks git-tracked files (respects .gitignore automatically) and classifies
them into the categories the Phase 0 mandate asks for: strategies, utilities,
configs, notebooks, scripts, data fixtures, docs. Read-only — never modifies
or deletes anything. Re-run any time to regenerate INVENTORY.md against the
current tree.

Usage: python tools/generate_inventory.py
"""

from __future__ import annotations

import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Classification is a fixed lookup, not inferred — the codebase is small
# enough (6 .py files) that guessing by heuristic would be less trustworthy
# than a maintainer stating what each file is, once, here.
STRATEGY_FILES = {"momentum_backtest.py", "paper_trader.py"}
UTILITY_FILES = {
    "transaction_costs.py",
    "fetch_universe.py",
    "download_data.py",
    "factor_attribution.py",
}
SCRIPT_FILES = {"run_today.ps1"}
NOTEBOOK_SUFFIXES = {".ipynb"}
CONFIG_SUFFIXES = {".toml", ".ini", ".cfg", ".yaml", ".yml"}
CONFIG_NAMES = {".env.example", "requirements-lock.txt"}
DATA_SUFFIXES = {".csv", ".json", ".db"}  # .db: PIT universe store (WP-007)
DOC_SUFFIXES = {".md", ".html"}
REPO_META_NAMES = {".gitignore", ".gitattributes", ".editorconfig", "CODEOWNERS", "LICENSE"}
# Phase 0 engineering scaffolding — classified by location, not by
# enumerating every filename, since new tests/tools files are expected to
# keep being added and shouldn't require updating this list each time.
ENGINEERING_DIR_PREFIXES = {"tests/": "tests", "tools/": "tooling", ".github/": "repo_meta"}
# Empty quantos_core/ + top-level module skeleton (ADR-031). Everything
# under these prefixes is a Phase 0/pre-Phase-1 placeholder — __init__.py
# docstrings and .gitkeep files, zero implementation. One bucket, not one
# per module, since there's nothing to distinguish yet.
SCAFFOLD_DIR_PREFIXES = (
    "quantos_core/",
    "services/",
    "dashboard/",
    "research/",
    "api/",
    "experiments/",
    "strategies_registry/",
    "infra/",
)


def git_tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True)
    return [line for line in out.stdout.splitlines() if line]


def classify(path: str) -> str:
    name = Path(path).name
    suffix = Path(path).suffix
    if name in STRATEGY_FILES:
        return "strategies"
    if name in UTILITY_FILES:
        return "utilities"
    if name in SCRIPT_FILES:
        return "scripts"
    if name in REPO_META_NAMES:
        return "repo_meta"
    for prefix, bucket in ENGINEERING_DIR_PREFIXES.items():
        if path.startswith(prefix):
            return bucket
    if path.startswith(SCAFFOLD_DIR_PREFIXES):
        return "scaffold"
    if suffix in NOTEBOOK_SUFFIXES:
        return "notebooks"
    if suffix in CONFIG_SUFFIXES or name in CONFIG_NAMES:
        return "configs"
    if suffix in DATA_SUFFIXES:
        return "data_fixtures"
    if suffix in DOC_SUFFIXES:
        return "docs"
    if suffix == ".py":
        return "other_python"
    return "other"


def main() -> None:
    files = git_tracked_files()
    buckets: dict[str, list[str]] = defaultdict(list)
    for f in files:
        buckets[classify(f)].append(f)

    lines = ["# QuantOS (AlgoTrader) — Phase 0 Baseline Inventory", ""]
    lines.append(
        "Generated by `tools/generate_inventory.py` against git-tracked files "
        f"({len(files)} total). Nothing here was moved, renamed, or deleted — "
        "this is a read-only classification of what already exists."
    )
    lines.append("")

    section_order = [
        (
            "strategies",
            "Strategies",
            "Trading strategy entry points — signal generation, backtest, or live/paper execution loop.",
        ),
        (
            "utilities",
            "Utilities",
            "Support modules imported by strategies — cost model, data fetch, factor research.",
        ),
        ("scripts", "Scripts", "Non-Python operational scripts."),
        ("configs", "Configs", "Configuration / environment templates / dependency lock."),
        ("notebooks", "Notebooks", "Jupyter notebooks."),
        ("data_fixtures", "Data Fixtures", "Cached market data, results, and persisted state — CSV/JSON."),
        ("docs", "Documentation", "Markdown/HTML research, audit, and planning documents."),
        ("tests", "Tests", "Phase 0 characterization tests and golden files (tests/)."),
        (
            "tooling",
            "Tooling",
            "Phase 0 engineering scripts — inventory, golden-file capture, determinism verification (tools/).",
        ),
        ("repo_meta", "Repo Metadata", "Git/editor/CI configuration — not application code or data."),
        (
            "scaffold",
            "Module Scaffold (empty)",
            "quantos_core/ + top-level module skeleton, per ADR-031 — __init__.py docstrings and "
            ".gitkeep only, zero implementation, nothing migrated from the frozen scripts.",
        ),
        ("other_python", "Other Python", "Python files not classified above — review needed."),
        ("other", "Other / Unclassified", "Everything else — review needed."),
    ]

    for key, title, desc in section_order:
        items = sorted(buckets.get(key, []))
        lines.append(f"## {title} ({len(items)})")
        lines.append("")
        lines.append(desc)
        lines.append("")
        if key == "data_fixtures" and len(items) > 20:
            # 459+ cached OHLCV CSVs individually would make this file useless
            # to read — summarize by directory instead, list everything else.
            by_dir: dict[str, int] = defaultdict(int)
            named = []
            for item in items:
                # as_posix(): plain str() yields "data\cache" on Windows, so the
                # startswith below never matched there and the committed file
                # (itemized) could never equal a Linux CI regeneration (summarized).
                parent = Path(item).parent.as_posix()
                if parent.startswith("data/cache") and Path(item).suffix == ".csv":
                    by_dir[parent] += 1
                else:
                    named.append(item)
            for d, count in sorted(by_dir.items()):
                lines.append(f"- `{d}/` — {count} cached CSV files")
            for item in sorted(named):
                lines.append(f"- `{item}`")
        elif items:
            for item in items:
                lines.append(f"- `{item}`")
        else:
            lines.append("_none_")
        lines.append("")

    unclassified = len(buckets.get("other", [])) + len(buckets.get("other_python", []))
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total tracked files: {len(files)}")
    lines.append(f"- Unclassified (needs review): {unclassified}")
    lines.append("")

    out_path = ROOT / "INVENTORY.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(files)} files classified, {unclassified} unclassified)")
    if unclassified:
        sys.exit(1)


if __name__ == "__main__":
    main()
